### ISSUE TITLE
"select-googlefont" didn't work and a suggestion for UI improvement. 

### ISSUE THREAD

**Issue by partharoy** [gambitph/Titan-Framework#193]
Hi. 
When I write a code for google font it won't work. It shows the error=. 
Titan Framework Error: Option type or extended class select-googlefont does not exist.

But "font" type is still working. Hope you will fix this bug. 

I have a suggestion for the UI improvement. If the tab will comes in vertically it will shows better like redux or vafpress. When I created many tabs it goes down below after fill first raw and looks ugly. So is there any way to create tabs from vertically left?

**Comment by dhrubobd** [comment]
Yes, select-googlefont type does not work!!! Showing "Titan Framework Error: Option type or extended class select-googlefont does not exist." 

If select-googlefont doesn't work you should remove this type from your reference webpage http://www.titanframework.net/select-googlefont-option/
Otherwise, developer should get confused. 

The solution is to use 'font' as type (http://www.titanframework.net/font-option/) instead of 'select-googlefont' type

**Comment by bfintal** [comment]
Removed it :)
