### ISSUE TITLE
Metabox values wont save on attachments

### ISSUE THREAD

**Issue by igorbenic** [gambitph/Titan-Framework#285]
Hello,

I have tried different option types and different metabox contexts or priorities on the attachment post type and the metabox values are not saved.

Is this intentionally or is it a bug?

**Comment by bfintal** [comment]
You're right, it seems that it's not saved for attachments. It should though and it works for CPTs, pages and posts.

**Comment by igorbenic** [comment]
I have done some investigation on this issue. It appears that the attachment post type works in a different way and it is not using actions or filters other Post Types do. I assume that those actions are not included inside the media.php file. 

Therefore, these fields should be added by using two filters:

**attachment_fields_to_edit**
https://codex.wordpress.org/Plugin_API/Filter_Reference/attachment_fields_to_edit

**attachment_fields_to_save**
https://codex.wordpress.org/Plugin_API/Filter_Reference/attachment_fields_to_save

There is a tutorial that is well written on this topic: 
http://code.tutsplus.com/articles/creating-custom-fields-for-attachments-in-wordpress--net-13076

I assume this would require some major code refactoring just for the attachments.

**Comment by bfintal** [comment]
The thing is `save_post` isn't called for attachments even though technically it is a post. The other post hooks get fired though so that's why getting values and meta boxes work.. values aren't just saved.

It seems like we don't need `attachment_fields_to_edit` and `attachment_fields_to_save` at all. `edit_attachment` works similarly to `save_post` but is just for saving attachments.
